import assert from 'node:assert/strict';
const pw=await import(process.env.PLAYWRIGHT || '/Users/jaytarzwell/claude-code-resources/node_modules/playwright/index.mjs');
const browser=await pw.chromium.launch({channel:process.env.BROWSER_CHANNEL || 'chrome'});
const page=await browser.newPage({viewport:{width:1000,height:900}}), errors=[], network=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!/^(file|data|blob):/.test(r.url()))network.push(r.url());});
const prefs=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('email-scrub.preferences.v3')));
async function row(names,label=''){await page.click('#add-person');const r=page.locator('#roles .role-row').last();await r.locator('.names').fill(names);await r.locator('.labin').fill(label);return r;}
async function scrub(text){await page.fill('#input',text);await page.click('#go');return page.locator('#out').evaluate(e=>{const c=e.cloneNode(true);c.querySelectorAll('.review-controls,.sr-only').forEach(n=>n.remove());return c.textContent;});}
try {
 await page.goto('file://'+new URL('../email-scrub.html',import.meta.url).pathname);
 assert.equal(await page.inputValue('#me'),'');assert.equal(await page.locator('#roles .role-row').count(),0);assert.equal(await page.locator('#roles select').count(),0);assert.equal(await page.textContent('#saved-people-summary'),'Saved people (0)');assert(!(await page.locator('#saved-people-panel').evaluate(e=>e.open)));
 await page.fill('#me','Fiction Sender, Fiction');const r=await row('Jónes, Jones','GRIEVOR');
 assert.equal(await scrub('Fiction Sender told Fiction to ask Jones.'),'Note: placeholders such as <PERSON-1> or <DATE-2> stand for removed details. Keep them exactly as written in any reply.\n\n<ME> told <ME> to ask <GRIEVOR>.');
 assert.equal((await prefs()).saved.length,0);assert(!JSON.stringify(await prefs()).includes('Jones'));
 await r.getByRole('button',{name:'Save person',exact:true}).click();assert.equal(await page.locator('#roles .role-row').count(),0);assert.equal((await prefs()).saved[0].label,'GRIEVOR');assert.equal((await prefs()).saved[0].lastUsed,'');
 await page.click('#clear');assert.equal(await page.inputValue('#me'),'Fiction Sender, Fiction');assert.equal((await prefs()).saved.length,1);
 await row('Zorvex Quill');await page.reload();assert.equal(await page.locator('#roles .role-row').count(),0);assert.equal(await page.inputValue('#me'),'Fiction Sender, Fiction');assert.equal(await page.inputValue('#input'),'');assert(await page.isHidden('#res'));
 await page.locator('#saved-people-panel summary').click();await page.fill('#saved-search','jon');assert((await page.textContent('#saved-people')).includes('Jónes'));await page.fill('#saved-search','unmatched');assert.equal(await page.locator('#saved-people button').count(),0);await page.fill('#saved-search','');
 await scrub('ordinary text');assert.equal((await prefs()).saved[0].lastUsed,'');await scrub('Jones spoke.');const date=(await prefs()).saved[0].lastUsed;assert.match(date,/^\d{4}-\d{2}-\d{2}$/);assert((await page.textContent('#saved-people')).includes('Last used: '+date));
 await page.evaluate(()=>{const p=JSON.parse(localStorage.getItem('email-scrub.preferences.v3'));p.saved[0].lastUsed='2026-10-01';localStorage.setItem('email-scrub.preferences.v3',JSON.stringify(p));});await page.reload();
 const override=await row('Jones','THREAD');assert((await scrub('Jones spoke.')).includes('<THREAD>'));assert.equal((await prefs()).saved[0].lastUsed,'2026-10-01');await override.getByRole('button',{name:'Remove person',exact:true}).click();
 await page.locator('#saved-people-panel summary').click();await page.locator('#saved-people').getByRole('button',{name:'Edit',exact:true}).click();await page.setViewportSize({width:375,height:850});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert(await page.getByRole('button',{name:'Save changes',exact:true}).evaluate(e=>e.offsetHeight<80));if(process.env.SHOT)await page.screenshot({path:process.env.SHOT,fullPage:true});await page.setViewportSize({width:1000,height:900});await page.getByRole('textbox',{name:'Edit saved names',exact:true}).fill('Velqor Drenn');await page.getByRole('textbox',{name:'Edit saved label',exact:true}).fill('Team lead');await page.getByRole('button',{name:'Save changes',exact:true}).click();assert.equal((await prefs()).saved[0].label,'TEAM-LEAD');assert((await scrub('Velqor Drenn spoke.')).includes('<TEAM-LEAD>'));
 const before=await page.evaluate(()=>localStorage.getItem('email-scrub.preferences.v3'));await row('Zorvex Quill','THREAD');await page.click('#demo');assert(await page.isDisabled('#forget'));assert.equal(await page.getAttribute('#forget','title'),'Leave the demo to manage saved preferences.');assert.equal(await page.inputValue('#me'),'Mira Quill, Mira');assert.equal(await page.locator('#roles .role-row').count(),2);assert((await page.locator('#out').evaluate(e=>{const c=e.cloneNode(true);c.querySelectorAll('.review-controls,.sr-only').forEach(n=>n.remove());return c.textContent;})).includes('From: <ME>'));assert((await page.locator('#out').evaluate(e=>{const c=e.cloneNode(true);c.querySelectorAll('.review-controls,.sr-only').forEach(n=>n.remove());return c.textContent;})).includes('<ADDRESS> <POSTAL>'));
 assert(!(await page.textContent('#review-list')).includes('Demo SIN'));assert(!(await page.textContent('#review-list')).includes('Demo SSN'));assert((await page.textContent('#review-list')).includes('Fictional Widgets'));
 await page.evaluate(()=>document.getElementById('forget').onclick());await page.locator('#roles button').filter({hasText:/^Save$/}).first().click();await page.fill('#me','Demo only');await page.click('#go');assert.equal(await page.evaluate(()=>localStorage.getItem('email-scrub.preferences.v3')),before);
 await page.fill('#input','Real input edit');assert(!(await page.isDisabled('#forget')));assert.equal(await page.inputValue('#me'),'Fiction Sender, Fiction');assert.equal(await page.locator('#roles .role-row').count(),1);
 await page.click('#demo');await page.click('#clear');assert(!(await page.isDisabled('#forget')));assert.equal(await page.locator('#roles .role-row').count(),0);assert.equal(await page.evaluate(()=>localStorage.getItem('email-scrub.preferences.v3')),before);
 await page.click('#help-open');await page.click('#help-close');assert(!(await page.locator('#help-dialog').evaluate(e=>e.open)));await page.click('#help-open');await page.keyboard.press('Escape');assert(!(await page.locator('#help-dialog').evaluate(e=>e.open)));
 await page.locator('#saved-people-panel').evaluate(e=>e.open=true);await page.locator('#saved-people').getByRole('button',{name:'Remove',exact:true}).click();assert.equal((await prefs()).saved.length,0);
 const legacy={people:[{role:'Me',title:'',names:'Fiction Sender, Fiction'},{role:'Client',title:'',names:'Zorvex Quill'},{role:'Boss',title:'GRIEVOR',names:'Velqor Drenn'}],kill:'private term',excluded:[{text:'Analyst',n:7}],nextExcluded:9};
 await page.evaluate(p=>{localStorage.clear();localStorage.setItem('email-scrub.preferences.v2',JSON.stringify(p));},legacy);await page.reload();assert.equal(await page.evaluate(()=>localStorage.getItem('email-scrub.preferences.v2')),null);assert.equal(await page.inputValue('#me'),'Fiction Sender, Fiction');assert.deepEqual((await prefs()).saved.map(r=>r.label),['CLIENT','GRIEVOR']);assert.equal(await page.locator('#roles .role-row').count(),0);
 const migrated=await scrub('Fiction Sender\nZorvex Quill\nVelqor Drenn\nAnalyste Analyst\n123 Demo Street\nSampleville, ON K1A 0B1');for(const tok of ['<ME>','<CLIENT>','<GRIEVOR>','Analyste <EXCLUDED-7>','<ADDRESS> <POSTAL>'])assert(migrated.includes(tok));
 await page.evaluate(()=>{localStorage.clear();localStorage.setItem('email-scrub.preferences.v1',JSON.stringify({people:[],kill:'',excluded:['Analyst']}));});await page.reload();assert(await page.isVisible('#migration-notice'));await page.click('#check-exclusions');assert(await page.locator('#exclusions-panel').evaluate(e=>e.open));await page.click('#dismiss-notice');await page.reload();assert(await page.isHidden('#migration-notice'));assert.equal(await page.evaluate(()=>localStorage.getItem('email-scrub.preferences.v1')),null);
 await page.click('#forget');assert.equal(await page.evaluate(()=>localStorage.getItem('email-scrub.preferences.v3')),null);assert.equal(await page.inputValue('#me'),'');assert.equal(await page.textContent('#saved-people-summary'),'Saved people (0)');assert.equal(await page.inputValue('#kill'),'');assert.equal(await page.textContent('#saved-terms'),'No highlighted exclusions yet.');
 assert.equal(await page.evaluate(()=>sessionStorage.length),0);assert.deepEqual(errors,[]);assert.deepEqual(network,[]);
 console.log('PASS '+(process.env.BROWSER_CHANNEL||'chrome')+' v0.4: empty defaults, Me, Save/Clear/reload, saved search/edit/remove/usage, override, demo isolation + disabled Forget, dialog button/Escape, v2/v1 migration + one-time notice, no stored threads, zero network/errors');
}finally{await browser.close();}
