/* Word lists for email-scrub. Lists grow; rules in engine.js should not.
 * commonEN, commonFR and months: never a name on their own. notNames: places, organisation words, titles and
 * email furniture. firstNames: common English and French given names. wordlikeFirstNames: given names that are also
 * ordinary words, replaced only when capitalized.
 */
(function (root) {
  'use strict';
  var api = {
    commonEN: [
    "a", "about", "above", "after", "again", "against", "all", "almost", "along", "already", "also", "although",
    "always", "am", "among", "an", "and", "another", "any", "anyone", "anything", "are", "around", "as", "at",
    "back", "based", "be", "because", "been", "before", "being", "below", "best", "better", "between", "beyond",
    "both", "but", "by", "came", "can", "cannot", "come", "coming", "concerning", "consequently", "considering",
    "could", "despite", "did", "do", "does", "doing", "done", "down", "due", "during", "each", "effective", "either",
    "else", "enough", "even", "ever", "every", "everyone", "everything", "except", "far", "few", "finally", "first",
    "firstly", "following", "for", "found", "from", "further", "furthermore", "gave", "get", "give", "given", "go",
    "going", "got", "had", "has", "have", "having", "he", "hence", "her", "here", "hers", "him", "his", "how",
    "however", "if", "importantly", "in", "including", "indeed", "instead", "into", "is", "it", "its", "itself",
    "just", "keep", "kept", "last", "lastly", "later", "least", "left", "less", "let", "like", "likely", "likewise",
    "little", "long", "made", "make", "many", "may", "me", "meanwhile", "might", "more", "moreover", "most", "much",
    "must", "my", "namely", "near", "nearly", "need", "neither", "never", "nevertheless", "next", "no",
    "nonetheless", "none", "nor", "not", "notably", "note", "noted", "nothing", "notwithstanding", "now", "of",
    "off", "often", "on", "once", "one", "only", "or", "other", "others", "otherwise", "our", "out", "over",
    "overall", "own", "particularly", "pending", "per", "perhaps", "please", "possibly", "pursuant", "quite",
    "rather", "regarding", "regardless", "related", "remain", "remains", "respectively", "said", "same", "say",
    "second", "secondly", "see", "seen", "several", "shall", "she", "should", "similarly", "since", "so", "some",
    "someone", "something", "specifically", "still", "subject", "subsequently", "such", "take", "taken", "than",
    "that", "the", "their", "them", "themselves", "then", "there", "thereafter", "thereby", "therefore", "therein",
    "thereof", "thereto", "these", "they", "third", "thirdly", "this", "those", "though", "three", "through", "thus",
    "to", "together", "too", "toward", "towards", "two", "ultimately", "under", "unless", "until", "up", "upon",
    "us", "use", "used", "using", "usually", "very", "was", "we", "well", "were", "what", "when", "where", "whereas",
    "whereby", "wherein", "whether", "which", "while", "who", "whom", "whose", "why", "will", "with", "within",
    "without", "would", "yes", "yet", "you", "your", "yours"
    ],
    commonFR: [
    "a", "afin", "ainsi", "alors", "apres", "au", "aucun", "aucune", "aupres", "aussi", "autant", "autre", "autres",
    "aux", "avant", "avec", "avoir", "bien", "car", "ce", "ceci", "cela", "celle", "celles", "celui", "cependant",
    "certain", "certaine", "certaines", "certains", "ces", "cet", "cette", "ceux", "chacun", "chaque", "chez",
    "comme", "comment", "compte", "concernant", "conformement", "contre", "dans", "de", "debut", "dehors", "deja",
    "depuis", "des", "desormais", "dessous", "dessus", "deux", "deuxieme", "doit", "doivent", "donc", "dont", "du",
    "duquel", "durant", "egalement", "elle", "elles", "en", "encore", "enfin", "ensuite", "entre", "est", "et",
    "etaient", "etait", "etant", "ete", "etre", "eux", "fait", "faire", "finalement", "fin", "fois", "font", "grace",
    "hors", "ici", "il", "ils", "jusqu", "jusque", "la", "laquelle", "le", "lequel", "les", "lesquelles", "lesquels",
    "leur", "leurs", "lors", "lorsque", "lui", "ma", "mais", "malgre", "me", "meme", "memes", "mes", "mien", "moins",
    "mon", "moyen", "ne", "neanmoins", "ni", "non", "nos", "notamment", "notre", "nous", "nouveau", "on", "ont",
    "ou", "outre", "par", "parce", "parmi", "pas", "pendant", "peu", "peut", "peuvent", "plus", "plusieurs",
    "plutot", "pour", "pourquoi", "pourtant", "premier", "premiere", "pres", "puis", "puisque", "quand", "quant",
    "que", "quel", "quelle", "quelles", "quelque", "quelques", "quels", "qui", "quoi", "sa", "sans", "sauf", "se",
    "selon", "sera", "serait", "ses", "seul", "seule", "seulement", "si", "sinon", "soit", "son", "sont", "sous",
    "souvent", "suite", "suivant", "sur", "ta", "tandis", "tant", "te", "tel", "telle", "telles", "tels", "toujours",
    "tous", "tout", "toute", "toutes", "trois", "trop", "tu", "un", "une", "vers", "voici", "voila", "vos", "votre",
    "vous", "y"
    ],
    months: [
    "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November",
    "December", "Jan", "Feb", "Mar", "Apr", "Jun", "Jul", "Aug", "Sep", "Sept", "Oct", "Nov", "Dec", "janvier",
    "fevrier", "mars", "avril", "mai", "juin", "juillet", "aout", "septembre", "octobre", "novembre", "decembre",
    "janv", "fevr", "avr", "juil", "sept", "oct", "nov", "dec", "Monday", "Tuesday", "Wednesday", "Thursday",
    "Friday", "Saturday", "Sunday", "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"
    ],
    notNames: [
    "Inc", "Ltd", "LLC", "LLP", "Corp", "Corporation", "Company", "Co", "Group", "Team", "Department", "Office",
    "Services", "Service", "Solutions", "Consulting", "Partners", "Associates", "Holdings", "Limited", "Canada",
    "Ontario", "Quebec", "Québec", "Alberta", "Manitoba", "Saskatchewan", "Nova", "Scotia", "Brunswick",
    "Newfoundland", "Labrador", "Columbia", "Yukon", "Nunavut", "Territories", "Toronto", "Ottawa", "Montreal",
    "Montréal", "Vancouver", "Calgary", "Edmonton", "Winnipeg", "Halifax", "Gatineau", "Kingston", "Hamilton",
    "Waterloo", "London", "Victoria", "Regina", "Saskatoon", "Moncton", "Fredericton", "Charlottetown", "Sherbrooke",
    "Laval", "Longueuil", "USA", "America", "American", "Canadian", "English", "French", "Français", "Anglais",
    "Google", "Microsoft", "Outlook", "Gmail", "Teams", "Zoom", "Excel", "Word", "PowerPoint", "PDF", "Monday",
    "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday", "Subject", "Objet", "Sent", "Envoyé",
    "Attachments", "Attachment", "Re", "Fwd", "Fw", "TR", "RE", "FW", "Please", "Thanks", "Thank", "Regards", "Best",
    "Cheers", "Sincerely", "Merci", "Cordialement", "Bonjour", "Hello", "Dear", "Hi", "Hey", "Note", "Notes",
    "Meeting", "Agenda", "Minutes", "Call", "Update", "Project", "Invoice", "Contract", "Agreement", "Schedule",
    "Appendix", "Section", "Clause", "Article", "Policy", "Act", "Law", "Court", "Board", "Committee", "Council",
    "Ministry", "Government", "Province", "City", "Town", "County", "State", "Street", "Avenue", "Road", "Drive",
    "Boulevard", "Suite", "Unit", "Floor", "Building", "Tower", "Centre", "Center", "Plaza", "Square", "North",
    "South", "East", "West", "Nord", "Sud", "Est", "Ouest", "New", "Old", "Great", "Saint", "St", "Ste", "Mount",
    "Lake", "River", "Bay", "Park", "Hill", "Valley", "Island", "Bank", "Fund", "Trust", "Insurance", "Health",
    "Hospital", "Clinic", "University", "College", "School", "Institute", "Association", "Foundation", "Union",
    "Church", "Mr", "Mrs", "Ms", "Mx", "Dr", "Prof", "Me", "Mme", "Mlle", "Madame", "Monsieur", "Sir", "Madam",
    "CEO", "CFO", "COO", "CTO", "VP", "President", "Director", "Manager", "Supervisor", "Coordinator", "Assistant",
    "Officer", "Advisor", "Analyst", "Counsel", "Lawyer", "Partner", "Associate", "Clerk", "Paralegal", "Accountant",
    "Consultant", "Client", "Customer", "Vendor", "Supplier", "Contractor", "Employee", "Employer", "Tenant",
    "Landlord", "Buyer", "Seller", "Purchaser", "Plaintiff", "Defendant", "Applicant", "Respondent"
    ],
    firstNames: [
    "Aaron", "Abigail", "Adam", "Adrian", "Aiden", "Alain", "Alan", "Albert", "Alex", "Alexandra", "Alexander",
    "Alexandre", "Alexis", "Alice", "Alicia", "Alison", "Allison", "Amanda", "Amber", "Amelia", "Amy", "Andre",
    "André", "Andrea", "Andrew", "Angela", "Angelique", "Anna", "Anne", "Annie", "Anthony", "Antoine", "Ashley",
    "Audrey", "Austin", "Barbara", "Benjamin", "Benoit", "Benoît", "Bernard", "Beth", "Bethany", "Betty", "Brandon",
    "Brenda", "Brent", "Brian", "Brittany", "Bruce", "Bryan", "Caleb", "Cameron", "Carl", "Carla", "Carlos",
    "Carmen", "Caroline", "Catherine", "Cathy", "Charles", "Charlie", "Charlotte", "Chloe", "Chloé", "Chris",
    "Christian", "Christina", "Christine", "Christopher", "Claire", "Claude", "Claudia", "Colin", "Connor", "Craig",
    "Crystal", "Cynthia", "Dale", "Damien", "Dan", "Daniel", "Danielle", "Darren", "David", "Deborah", "Debra",
    "Denis", "Dennis", "Derek", "Diana", "Diane", "Dominic", "Dominique", "Donald", "Donna", "Doris", "Dorothy",
    "Douglas", "Dylan", "Edward", "Elaine", "Eleanor", "Elena", "Elizabeth", "Ellen", "Emily", "Emma", "Emmanuel",
    "Eric", "Éric", "Erica", "Erin", "Ethan", "Étienne", "Eugene", "Evan", "Evelyn", "Fabien", "Felix", "Félix",
    "Fernand", "Florence", "Frances", "Francis", "Francine", "Francois", "François", "Françoise", "Gabriel",
    "Gabrielle", "Gail", "Gary", "Genevieve", "Geneviève", "George", "Georges", "Gerald", "Gérard", "Gilles", "Gina",
    "Glen", "Glenn", "Gloria", "Gordon", "Greg", "Gregory", "Guillaume", "Hannah", "Harold", "Harry", "Heather",
    "Helen", "Hélène", "Henri", "Henry", "Hugo", "Ian", "Isabelle", "Jacob", "Jacqueline", "Jacques", "James",
    "Jamie", "Jane", "Janet", "Janice", "Jason", "Jean", "Jeanne", "Jeff", "Jeffrey", "Jennifer", "Jeremy", "Jérôme",
    "Jerry", "Jesse", "Jessica", "Jill", "Joan", "Joanne", "Joe", "Joel", "Johanne", "John", "Jonathan", "Jordan",
    "Jose", "Joseph", "Josée", "Joshua", "Joyce", "Judith", "Judy", "Julia", "Julian", "Julie", "Julien", "Justin",
    "Karen", "Karine", "Kate", "Katherine", "Kathleen", "Kathryn", "Kathy", "Katie", "Keith", "Kelly", "Ken",
    "Kenneth", "Kevin", "Kim", "Kimberly", "Kyle", "Laura", "Laurent", "Lauren", "Laurie", "Lawrence", "Leah",
    "Linda", "Lindsay", "Lisa", "Logan", "Louis", "Louise", "Luc", "Lucas", "Lucie", "Luke", "Lynn", "Madeleine",
    "Mandy", "Manon", "Marc", "Marcel", "Margaret", "Maria", "Marie", "Marilyn", "Mario", "Marion", "Martha",
    "Martin", "Mary", "Maryse", "Mathieu", "Matthew", "Maurice", "Megan", "Melanie", "Mélanie", "Melissa", "Michael",
    "Michel", "Michelle", "Mike", "Mireille", "Monique", "Morgan", "Nancy", "Natalie", "Nathalie", "Nathan",
    "Nicholas", "Nicolas", "Nicole", "Noah", "Normand", "Olivia", "Olivier", "Pamela", "Pascal", "Patricia",
    "Patrick", "Paul", "Paula", "Pauline", "Peter", "Philip", "Philippe", "Pierre", "Rachel", "Ralph", "Raphaël",
    "Raymond", "Rebecca", "Réjean", "Renee", "Renée", "Richard", "Robert", "Roberta", "Roger", "Ronald", "Rosa",
    "Ruth", "Ryan", "Samantha", "Samuel", "Sandra", "Sara", "Sarah", "Scott", "Sean", "Sebastien", "Sébastien",
    "Serge", "Sharon", "Shawn", "Sheila", "Shirley", "Simon", "Sophie", "Stephane", "Stéphane", "Stephanie",
    "Stéphanie", "Stephen", "Steve", "Steven", "Susan", "Suzanne", "Sylvain", "Sylvie", "Tammy", "Teresa", "Terry",
    "Theresa", "Thomas", "Tiffany", "Timothy", "Tina", "Todd", "Tracy", "Travis", "Tyler", "Valerie", "Valérie",
    "Vanessa", "Victor", "Victoria", "Vincent", "Virginie", "Walter", "Wayne", "Wendy", "William", "Yannick", "Yves",
    "Zachary", "Zoe"
    ],
    wordlikeFirstNames: [
    "Will", "May", "Mark", "Grant", "Bill", "Rose", "Hope", "Joy", "Art", "Faith", "Pat", "Sue", "Guy", "Rich",
    "Frank", "Jack", "April", "June", "Summer", "Dawn", "Sunny", "Chase", "Hunter", "Drew", "Gene", "Ray", "Sky",
    "Eve", "Max", "Rob", "Dean", "Earl", "Miles", "Bob", "Ivy", "Holly", "Iris", "Pearl", "Ruby", "Amber", "Crystal",
    "Hazel", "Jade", "Autumn", "Destiny", "Harmony", "Grace", "Victor", "Charity", "Rock", "Gale", "Lance",
    "Sterling", "Penny", "Norm", "Bud", "Rusty", "Woody", "Sandy"
    ]
  };
  if (typeof module !== 'undefined' && module.exports) module.exports = api; else root.EmailScrubLists = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
